account/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

chores/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('planner.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

planner/urls.py
from django.urls import path

from . import views

app_name = 'planner'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path('t<int:pk>/', views.TaskView.as_view(), name='task_detail'),
    path('t/', views.tasks_page, name='task_list'),
    path('new/', views.new_task, name='new_task'),
]

account/models.py
from django.db import models

# Create your models here.

planner/models.py
from django.db import models
from django.contrib.auth.models import User

class Schedule(models.Model):
    """
    This is used to handle a collection of Persons and Tasks. 
    The schedule is the hub for connecting Persons into a group.
    When changing the Person associated with a Task, the Person choices are limited
    to those of the same Schedule as the editor.

    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Person(models.Model):
    """
    A "User" model just handles authentication. This is an extension upon that,
    in the form of a One-to-One relationship. This will connect a user with whatever
    data a user needs to use the app, such as permissions, groups, logs, object ownership etc.
    """
    # One-to-One link with a user account
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    schedule = models.ForeignKey(Schedule, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.user.username

class Task(models.Model):
    title = models.CharField(max_length=100)
    details =  models.CharField(max_length=200)
    points = models.IntegerField(default=10)
    asignee = models.ForeignKey(Person, null=True, blank=True, on_delete=models.SET_NULL)
    schedule = models.ForeignKey(Schedule, null=True, blank=True, on_delete=models.SET_NULL)

    last_completed = models.DateTimeField('last completed')
    wait_days = models.IntegerField(default=1) # 1-->daily
    # to see if a task is due, round down to the beginning of day last_completed
    # then add datetime.timedelta(days=wait_days)
    # then check if the result is less than now

    def __str__(self):
        return self.title

planner/forms.py
from django import forms

from .models import Task

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = (
            'title',
            'details',
            'points',
            # 'asignee',
            # 'schedule',
            # 'last_completed',
            'wait_days',
            )

account/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'account/signup.html'

planner/views.py
import datetime

from django.shortcuts import get_object_or_404, render

from django.http import HttpResponse
from django.views import generic
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect

from .models import Task, Schedule, Person
from .forms import TaskForm


@require_POST
@login_required()
def new_task(request):
    person = get_object_or_404(Person, user=request.user)
    schedule = get_object_or_404(Schedule, pk=person.schedule.pk)
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.asignee = person
            task.schedule = schedule
            task.last_completed = datetime.date.today()
            task.save()
            return redirect('planner:task_list')

def tasks_page(request):
    
    context = {
            'form': TaskForm(),
            'task_list': Task.objects.all(),
            "big_word": "Big Word",
        }

    return render( request, 'planner/tasks.html', context)



class LoginView(TemplateView):
    pass


# class TaskListView(LoginRequiredMixin, generic.ListView):
#     template_name = 'planner/tasks.html'
#     context_object_name = 'task_list'
#     ordering = ['-points']

#     def get_queryset(self):
#         person = get_object_or_404(Person, user=self.request.user)
#         return Task.objects.filter(asignee=person)


class Manager(TemplateView):
    pass

class questionaire(TemplateView):
    pass

class register(TemplateView):
    pass





















class HomePageView(TemplateView):
    template_name = "planner/index.html"


class ChecklistView(generic.DetailView):
    """
    Shows a list of all tasks that must be done, sorted by highest point value.
    
    Task A         1000 pts   <--- click a task to open task detail
    Task B         1000 pts
    Task C          400 pts
    Task D           30 pts
    """
    model = Schedule
    template_name = 'planner/checklist.html'


class TaskView(generic.DetailView):
    """
    Shows the task and the description and completion requirements.

    Take a picture to prove it option here.
    For simple prototype, just click done button.

    """
    model = Task
    template_name = 'planner/task_detail.html'


class TaskListView(generic.ListView):
    template_name = 'planner/tasks.html'
    context_object_name = 'task_list'

    form = TaskForm()
    big_word = "BIG WORD"

    def get_queryset(self):
        return Task.objects.all()



def done_list():
    """
    Show the list of all tasks done and their value and all badges earned today
    """
    return None

def badge_history():
    """
    Shows a left-right scrolling columns containing the badges earned in past days.

    Shows the total number of badges earned of each type.

    Shows the rewards that are yet to be redeemed.
    """
    return None

planner/templates/planner/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
  <title>Starter Template - Materialize</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Handlee|Open+Sans+Condensed:300,300i,700&display=swap" rel="stylesheet">
  {% load static %}
  <link href="{% static 'planner/css/materialize.custom.css' %}" type="text/css" rel="stylesheet"
    media="screen,projection" />
  <link href="{% static 'planner/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection" />
</head>

<body>
  {% include "planner/nav.html" %}

  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <h2 class="header center">{% block page_name %}{% endblock %}</h2>
    </div>
  </div>

  <div class="container" style="margin-top: 8rem; margin-bottom: 12rem">
    {% block content %}CONTENT GOES HERE{% endblock %}
  </div>

  {% include "planner/footer.html" %}

  <!--  Scripts-->
  {% include "planner/scripts.html" %}

</body>

</html>

planner/templates/planner/footer.html
<footer class="page-footer" style="position: fixed; left: 0; bottom: 0; width: 100%; z-index: 100">
    <div class="container">
        <div class="row">



            <div class="col s4">
                <h6 class="white-text">Account</h6>
                <ul>
                    {% if user.is_authenticated %}
                        <li><a class="white-text" href="{% url 'logout' %}">Logout {{ user.username }}</a></li>
                    {% else %}
                        <li><a class="white-text" href="{% url 'login' %}">Login</a></li>
                    {% endif %}

                </ul>
            </div>


        </div>
    </div>
</footer>

planner/templates/planner/index.html
{% extends "planner/base.html" %}

{% block page_name %}Nest Keeper{% endblock %}
{% block page_description %}Keep your nest at its very best!{% endblock %}

{% block content %}
{% lorem 6 p %}
{% endblock %}

planner/templates/planner/nav.html
<!-- <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container">
        <a id="logo-container" href="#" class="brand-logo">
            <i class="large material-icons">memory</i>NESTKEEPER
        </a>
        <ul class="right hide-on-med-and-down">{% include "planner/nav_links.html" %}</ul>
        <ul id="nav-mobile" class="sidenav">{% include "planner/nav_links.html" %}</ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
</nav> -->


<nav class="nav-extended pushpin pin-top z-depth-3" style="z-index: 100">
        <div class="nav-wrapper ">
          <a href="#" class="brand-logo">Nest Keeper</a>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="sass.html">Sass</a></li>
            <li><a href="badges.html">Components</a></li>
            <li><a href="collapsible.html">JavaScript</a></li>
          </ul>
        </div>
        <div class="nav-content">
          <ul class="tabs tabs-transparent">
            <li class="tab"><a href="#test1">All</a></li>
            <li class="tab"><a class="active" href="#test2">Mine</a></li>
          </ul>
        </div>
      </nav>
    
      <ul class="sidenav" id="mobile-demo">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">JavaScript</a></li>
      </ul>

planner/templates/planner/nav_links.html
<li><a href="{% url 'planner:index' %}">Home</a></li>
{% if user.is_authenticated %}
    <li><a href="{% url 'logout' %}">Logout {{ user.username }}</a></li>
{% else %}
    <li><a href="{% url 'login' %}">Login</a></li>
{% endif %}
<li><a href="{% url 'planner:task_list' %}">Today</a></li>
<li><a href="{% url 'planner:index' %}">Manage</a></li>
<li><a href="{% url 'admin:index' %}">Admin</a></li>

planner/templates/planner/new_task.html
{% extends 'planner/base.html' %}

{% block page_name %}New Task{% endblock %}
{% block page_description %}Create a new task to add it to your planner.{% endblock %}

{% block content %}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button class="btn waves-effect waves-light" type="submit" name="action">Save
            <i class="material-icons right">cloud_done
            </i>
          </button>
    </form>
{% endblock %}

planner/templates/planner/scripts.html
{% load static %}
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="{% static 'planner/js/materialize.js' %}"></script>
<script>
$(document).ready(function(){
    $('.sidenav').sidenav();
    $('.pushpin').pushpin();
    $('.tabs').tabs();
    $('.fixed-action-btn').floatingActionButton({
      direction: 'left',
      hoverEnabled: false,
    });
    $('.collapsible').collapsible();
    $('.dropdown-trigger').dropdown();
    $('.modal').modal();
    $('.pin-footer').pushpin({
        offset: 600,
    });
  });
</script>

planner/templates/planner/tasks.html
{% extends "planner/base.html" %}
{% block content %}

<!-- 
assignment_ind
attachment
av_timer
autorenew
beenhere
cancel
check
close
comment
create, edit
delete_forever
error, new_releases, priority_high, star, whatshot
feedback
history
home
hourglass_full
people
person_outline
person_add
send
settings
timer
-->

<h2 class="center">Today's Tasks</h2>

<div class="fixed-action-btn">
    <a class="btn-floating btn-large">
        <i class="large material-icons">mode_edit</i>
    </a>
    <ul>
        <li><a class="btn-floating orange lighten-2"><i class="material-icons">comment</i></a></li>
        <li><a class="btn-floating teal lighten-2"><i class="material-icons">people</i></a></li>
        <li><a class="btn-floating green lighten-2 modal-trigger" href="#modalnewtask"><i class="material-icons">add</i></a></li>
    </ul>
</div>


      

<ul class="collapsible popout">

    {% for task in task_list %}

    <li>


        <div class="collapsible-header ">
                <i class="material-icons Large">person_outline</i>
                <h6>{{task.title}}</h6>
            <span class="badge">
                <i style="color: orange" class="material-icons">whatshot</i>
                <i style="color: goldenrod" class="material-icons small">star</i><span class="new badge" data-badge-caption="{{task.points}}"></span>




            </span>
        </div>
        <div class="collapsible-body">
            <span class="badge">
            <a class="btn-floating waves-effect waves-light red lighten-2 modal-trigger" href="#modaldelete"><i class="material-icons">delete_forever</i></a>
            <a class="btn-floating waves-effect waves-light orange lighten-2 modal-trigger" href="#modaledit"><i class="material-icons">edit</i></a>
            <a class="btn-floating waves-effect waves-light green lighten-2 modal-trigger" href="#modalcomplete"><i class="material-icons">check</i></a>



            <!-- <div style="position: relative; height: 15px;">
                    <div class="fixed-action-btn horizontal direction-top direction-left" style="position: absolute; display: inline-block; right: -40px;">
                        <a class="btn-floating btn-small red">
                        <i class="large material-icons">mode_edit</i>
                        </a>
                        <ul>
                        <li>
                            <a class="btn-floating red" style="opacity: 0; transform: scale(0.4) translateY(0px) translateX(40px);">
                            <i class="material-icons">insert_chart</i>
                            </a>
                        </li>
                        <li>
                            <a class="btn-floating yellow darken-1" style="opacity: 0; transform: scale(0.4) translateY(0px) translateX(40px);">
                            <i class="material-icons">format_quote</i>
                            </a>
                        </li>
                        <li>
                            <a class="btn-floating green" style="opacity: 0; transform: scale(0.4) translateY(0px) translateX(40px);">
                            <i class="material-icons">publish</i>
                            </a>
                        </li>
                        <li>
                            <a class="btn-floating blue" style="opacity: 0; transform: scale(0.4) translateY(0px) translateX(40px);">
                            <i class="material-icons">attach_file</i>
                            </a>
                        </li>
                        </ul>
                    </div>
                </div> -->


            </span>
            <span>{{ task.details }}</span>
        </div>

    </li>

    {% endfor %}
</ul>

<!-- Modal Structure -->
<div id="modaldelete" class="modal">
    <div class="modal-content">
        <h4>Delete?</h4>
        <p>Are you sure you want to delete this task?</p>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-close waves-effect waves-green btn">Cancel</a>
        <a href="#!" class="modal-close waves-effect waves-green btn">Delete</a>
    </div>
</div>


<!-- Modal Structure -->
<div id="modaledit" class="modal">
<div class="modal-content">
    <h4>Not Quite...</h4>
    <p>Do you want to edit this task?</p>
</div>
<div class="modal-footer">
    <a href="#!" class="modal-close waves-effect waves-green btn">Cancel</a>
    <a href="#!" class="modal-close waves-effect waves-green btn">Edit</a>
</div>
</div>

<!-- Modal Structure -->
<div id="modalcomplete" class="modal">
<div class="modal-content">
    <h4>Complete!</h4>
    <p>Is this task completed?</p>
</div>
<div class="modal-footer">
    <a href="#!" class="modal-close waves-effect waves-green btn">Cancel</a>
    <a href="#!" class="modal-close waves-effect waves-green btn">Complete</a>
</div>
</div>



<!-- Modal Structure -->
<div id="modalnewtask" class="modal">
    <form method="POST" class="post-form" action="{% url 'planner:new_task' %}">{% csrf_token %}
        <div class="modal-content">
            <h4>New Task!</h4>
            {{ form.as_p }}
        </div>
        <div class="modal-footer">
            <a href="#!" class="modal-close waves-effect waves-green btn">Cancel</a>
            <button class="modal-close waves-effect waves-green btn" type="submit" name="action">Save
                    <i class="material-icons right">cloud_done</i>
                </button>
        </div>
    </form>
</div>


    

<!-- <ul class="collection">

    {% for task in task_list %}

    <li class="collection-item avatar">
        <i class="material-icons circle green">check_box</i>
        <span class="title">{{ task.title}}</span>
        <p>{{ task.details }}</p>
        <a href="#!" class="secondary-content"><i class="material-icons">grade</i>{{ task.points }}</a>
    </li>

    {% endfor %}


    {% for task in task_list %}

    <li class="collection-item avatar">
        <i class="material-icons circle green">check_box</i>
        <span class="title">{{ task.title}}</span>
        <p>{{ task.details }}</p>
        <a href="#!" class="secondary-content"><i class="material-icons">grade</i>{{ task.points }}</a>
    </li>

    {% endfor %}

</ul> -->

{% endblock %}

planner/templates/planner/unused/checklist.html
{% extends "planner/base.html"}

{% block content %}
{% if task_list %}
    <ul>
    {% for task in task_list %}
        <li><a href="{% url 'planner:task_detail' task.id %}">{{ task.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No tasks are available.</p>
{% endif %}
{% endblock %}

planner/templates/planner/unused/newtask.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'planner:newtask' question.id %}" method="post">
<input placeholder="Placeholder" id="first_name" type="text" class="validate">
<label for="first_name">First Name</label>
<input type="submit" value="Vote">
</form>

planner/templates/planner/unused/task_detail.html
<p>{{ task.title }}</p>
<p>{{ task.details }}</p>
<p>{{ task.is_done }}</p>
<p>{{ task.schedule }}</p>
<p>{{ task.points }}</p>